# Generated by Django 3.1.6 on 2021-02-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ManyToManyField(to='users.PaymentPlan'),
        ),
    ]
